---
parser: babel-eslint
extends:
  - airbnb-base
  - vue

env:
  es6: true

rules:
  indent: ["error", 4]
  linebreak-style: [2, "unix"]
  semi: [2, "always"]
  strict: ["error"]
  import/no-extraneous-dependencies: 0
